### ISSUE TITLE
Stacktrace on startup with Java11

### ISSUE THREAD

**Issue by NeverGrowUp** [AddstarMC/RemoteConsole#93]
With both build 61 and 62, when server starts up, the below stacktrace appears and repeats several times until Rcon has finished loading. Only started when changing from Java8 to Java11. Once Rcon has finished loading, everything appears fine with no change in functionality or additional errors.
Paper version used was both 1.16.5-436 and 546(latest)

```
2021-03-13 20:54:07 [nioEventLoopGroup-3-1/WARN]: An exception was thrown by au.com.addstar.rcon.server.ServerNetworkManager.operationComplete()
java.lang.NullPointerException: null
        at au.com.addstar.rcon.server.RconServer.connectionClose(RconServer.java:206) ~[?:?]
        at au.com.addstar.rcon.server.ServerNetworkManager.operationComplete(ServerNetworkManager.java:48) ~[?:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1158) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:760) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:736) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:607) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1352) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:606) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:472) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:957) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannel.close(AbstractChannel.java:232) ~[patched_1.16.5.jar:git-Paper-546]
        at au.com.addstar.rcon.network.NetworkManager.close(NetworkManager.java:137) ~[?:?]
        at au.com.addstar.rcon.network.handlers.AbstractNetworkHandler$1.operationComplete(AbstractNetworkHandler.java:33) ~[?:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:183) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[patched_1.16.5.jar:git-Paper-546]
        at au.com.addstar.rcon.network.handlers.AbstractNetworkHandler.disconnect(AbstractNetworkHandler.java:28) ~[?:?]
        at au.com.addstar.rcon.server.ServerLoginHandler.handleLoginBegin(ServerLoginHandler.java:44) ~[?:?]
        at au.com.addstar.rcon.network.packets.login.PacketInLoginBegin.handlePacket(PacketInLoginBegin.java:23) ~[?:?]
        at au.com.addstar.rcon.network.NetworkManager.channelRead0(NetworkManager.java:100) ~[?:?]
        at au.com.addstar.rcon.network.NetworkManager.channelRead0(NetworkManager.java:21) ~[?:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.16.5.jar:git-Paper-546]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[patched_1.16.5.jar:git-Paper-546]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by NeverGrowUp** [comment]
In addition, stack only occurs when someone is already connected to Rcon and connected to the server.

Steps to reproduce:
Connect to Rcon. Restart server.

Steps to **not** produce error while connected to Rcon:
.disconnect <server>. Restart server.
